### ISSUE TITLE
Add Click Tracking as a feature

### ISSUE THREAD

**Issue by mathetos** [impress-org/give-google-analytics#2]
Would love to allow Admins to see how effective different referrers work for converting on their donation forms. The best way I've done this is with Click Tracking. Here's how it works.

1) The "Donate Now" button has the following added to it:
`onclick="ga('send', 'event', 'Click', 'Donated', '[twitter|facebook|linkedin]');"`

2) They share their Donation pages on social with the social referral as a query parameter, like so:
`example.com/donations/give-now?social=facebook`

That results in "Events" in Google Anaytics that look something like this:
![image](https://cloud.githubusercontent.com/assets/930724/20548222/6f7c99ba-b0d6-11e6-8fa5-638609f856c1.png)

## What it Might Look Like in This Plugin
1) A setting to enable "Social Media Referral Tracking"
2) When enabled, on each form edit screen there's a metabox section in the sidebar to give them an easy share url that appends that query parameter automatically
3) The `onClick` event is added to the Donate Now buttons automatically.

Just an idea to add more value to this Add-on.

**Comment by chriscct7** [comment]
If you are doing a GA ecommerce flow tracking on it (send order to GA post donation) you don't have to pass the referrer, it be automatically included in the GA reports and you can do breakdowns by referrer

**Comment by DevinWalker** [comment]
This has been brought into Canny as feedback: https://feedback.givewp.com/feature-requests/p/add-click-tracking-to-google-analytics-add-on
